//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.CompilerServices;

[assembly: AssemblyConfiguration("Debug")]
[assembly: AssemblyProduct("JustSayingIflo")]
[assembly: AssemblyCompany("JUST EAT plc")]
[assembly: AssemblyCopyright("Copyright © JUST EAT plc 2013")]

[assembly: CLSCompliant(false)]
[assembly: AssemblyVersion("0.2.100.0")]
[assembly: AssemblyFileVersion("0.2.100.0")]
[assembly: AssemblyInformationalVersion("1.0.0-alpha")]
[assembly: InternalsVisibleTo("JustSaying.UnitTests")]


